yarnPath: ".yarn/releases/yarn-berry.js"
packageExtensions:
  "jss-plugin-rule-value-function@*":
    dependencies:
      "tiny-warning": "*"
  "material-table@*":
    dependencies:
      "@babel/runtime": "*"